import csv
import io
import json
import re
from dataclasses import dataclass
from typing import Any, Optional

from django.conf import settings


class FileProcessingError(ValueError):
    """Raised when an uploaded file cannot be parsed"""

    pass


@dataclass
class RegexSuggestion:
    pattern: str
    explanation: str
    source: str


def parse_uploaded_file(uploaded_file) -> dict[str, Any]:
    """Parse a CSV or XLSX file into columns, rows, and row count.

    Raises:
        FileProcessingError: If the file is too large or uses an unsupported format.
        UnicodeDecodeError: If CSV content cannot be decoded as UTF-8.
    """

    if uploaded_file.size > settings.MAX_UPLOAD_BYTES:
        raise FileProcessingError("File is too large.")

    name = uploaded_file.name.lower()
    data = uploaded_file.read()

    if name.endswith(".csv"):
        return _parse_csv(data)
    if name.endswith(".xlsx"):
        return _parse_xlsx(data)
    if name.endswith(".xls"):
        raise FileProcessingError("Legacy .xls files are not supported. Please save as .xlsx or CSV.")

    raise FileProcessingError("Unsupported file type. Upload a CSV or XLSX file.")


def _parse_csv(data: bytes) -> dict[str, Any]:
    """Parse CSV bytes into a table."""

    text = data.decode("utf-8-sig")
    sample = text[:4096]
    try:
        dialect = csv.Sniffer().sniff(sample)
    except csv.Error:
        dialect = csv.excel

    reader = csv.DictReader(io.StringIO(text), dialect=dialect)
    if not reader.fieldnames:
        raise FileProcessingError("CSV file must include a header row.")

    rows = [{key: value for key, value in row.items()} for row in reader]
    return {"columns": reader.fieldnames, "rows": rows, "rowCount": len(rows)}


def _parse_xlsx(data: bytes) -> dict[str, Any]:
    """Parse XLSX into a table."""

    try:
        from openpyxl import load_workbook
    except ImportError as exc:
        raise FileProcessingError("XLSX support requires openpyxl. Install backend requirements first.") from exc

    workbook = load_workbook(io.BytesIO(data), read_only=True, data_only=True)
    sheet = workbook.active
    values = list(sheet.iter_rows(values_only=True))
    if not values:
        raise FileProcessingError("Spreadsheet is empty.")

    columns = [str(cell).strip() if cell is not None else f"Column {index + 1}" for index, cell in enumerate(values[0])]
    rows = []
    for raw in values[1:]:
        row = {}
        for index, column in enumerate(columns):
            value = raw[index] if index < len(raw) else ""
            row[column] = "" if value is None else str(value)
        rows.append(row)

    return {"columns": columns, "rows": rows, "rowCount": len(rows)}


def suggest_regex_from_text(description: str) -> RegexSuggestion:
    """Generate a regex from a natural-language description."""

    text = description.strip()
    if not text:
        raise ValueError("Description is required.")

    if settings.OPENAI_API_KEY:
        generated = _suggest_with_openai(text)
        if generated:
            return generated
    # Fall back to rule-based regex generation if the LLM call fails.
    return _suggest_with_rules(text)


def _suggest_with_openai(description: str) -> Optional[RegexSuggestion]:
    """Ask OpenAI model for a Python-compatible regex"""
    try:
        from openai import OpenAI

        client = OpenAI(api_key=settings.OPENAI_API_KEY)
        response = client.chat.completions.create(
            model=settings.OPENAI_MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {
                    "role": "system",
                    "content": (
                        "Convert a user's natural language matching request into a Python-compatible "
                        "regular expression. Return JSON with keys pattern and explanation only. "
                        "Do not include delimiters or flags."
                    ),
                },
                {
                    "role": "user",
                    "content": json.dumps({"description": description}),
                },
            ],
        )
        payload = json.loads(response.choices[0].message.content or "{}")
        pattern = payload.get("pattern", "")
        re.compile(pattern)
        return RegexSuggestion(
            pattern=pattern,
            explanation=payload.get("explanation", "Generated by the configured LLM."),
            source="llm",
        )
    except Exception as e:
        print(e)
        return None


def _suggest_with_rules(description: str) -> RegexSuggestion:
    """Return a regex from keyword rules, or an escaped literal fallback."""
    lowered = description.lower()
    rules = [
        (["email", "e-mail"], r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,7}\b", "Matches common email addresses."),
        (["phone", "telephone", "mobile"], r"\b(?:\+?\d{1,3}[-.\s]?)?(?:\(?\d{2,4}\)?[-.\s]?)?\d{3,4}[-.\s]?\d{4}\b", "Matches common phone numbers."),
        (["url", "link", "website"], r"https?://[^\s]+", "Matches HTTP and HTTPS URLs."),
        (["date"], r"\b(?:\d{4}[-/]\d{1,2}[-/]\d{1,2}|\d{1,2}[-/]\d{1,2}[-/]\d{2,4})\b", "Matches common numeric dates."),
        (["number", "numeric"], r"\b-?\d+(?:\.\d+)?\b", "Matches integer or decimal numbers."),
        (["name"], r"\b[A-Z][a-z]+(?:\s+[A-Z][a-z]+)+\b", "Matches simple capitalized full names."),
    ]
    for keywords, pattern, explanation in rules:
        if any(keyword in lowered for keyword in keywords):
            return RegexSuggestion(pattern, explanation, "rules")

    return RegexSuggestion(re.escape(description), "Fallback: matches the exact text literally.", "rules")


def process_table(rows: list[dict[str, Any]], pattern: str, replacement: str) -> dict[str, Any]:
    """Replace every regex match in every cell and return processed rows with count"""
    if not rows:
        raise ValueError("Rows are required.")

    try:
        regex = re.compile(pattern)
    except re.error as exc:
        raise ValueError(f"Invalid regular expression: {exc}") from exc

    processed = []
    total_matches = 0
    changed_rows = 0

    for row in rows:
        next_row = dict(row)
        row_changed = False
        for grid in next_row:
            original = "" if next_row.get(grid) is None else str(next_row.get(grid, ""))
            # Replace regex matches in the original value with the replacement text.
            updated, count = regex.subn(replacement, original)
            if count:
                total_matches += count
                row_changed = True
                next_row[grid] = updated
        if row_changed:
            changed_rows += 1
        processed.append(next_row)

    return {
        "rows": processed,
        "summary": {
            "totalMatches": total_matches,
            "changedRows": changed_rows,
            "totalRows": len(rows),
        },
    }
